/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package latexGlobalGraphics;

import latex.Latex;

/**
 *
 * @author Dwight
 */
public class Properties extends javax.swing.JFrame {

    /**
     * Creates new form Properties
     */
    
    private Latex _lat;
    public Properties() {
        initComponents();
    }
    public void setLocalReferenceOfMainMenu(Latex lat){
        this._lat = lat;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chbGIT = new javax.swing.JCheckBox();
        labServerType = new javax.swing.JLabel();
        tfURL = new javax.swing.JTextField();
        labURL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttCreate = new javax.swing.JButton();
        labName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        chbOutput = new javax.swing.JCheckBox();
        chbSVN = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chbGIT.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        chbGIT.setText("GIT server");
        chbGIT.setEnabled(false);

        labServerType.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labServerType.setText("Server type:");

        labURL.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labURL.setText("URL for server :");

        buttCreate.setText("Create");
        buttCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttCreateActionPerformed(evt);
            }
        });

        labName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        labName.setText("Name :");

        chbOutput.setText("Show Output on the side");

        chbSVN.setText("SVN server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labURL)
                    .addComponent(labName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labServerType)
                        .addGap(18, 18, 18)
                        .addComponent(chbGIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbSVN)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfURL)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chbOutput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttCreate)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labServerType)
                    .addComponent(chbGIT)
                    .addComponent(chbSVN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(labURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttCreate)
                    .addComponent(chbOutput))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCreateActionPerformed
    int isSvn=0,output=0;
    String name,Url,editor;
        if(chbSVN.isSelected())
            isSvn = 1;
        if(chbOutput.isSelected())
            output = 1;
        name = tfName.getText();
        Url = tfURL.getText();
       _lat.SetProperties(isSvn, output, name, Url);
       this.dispose();
    }//GEN-LAST:event_buttCreateActionPerformed

    public void setProperties(int isSvn,String name,String url,int out){
        if(isSvn == 1)
            chbSVN.setSelected(true);
        else
            chbGIT.setSelected(true);
        tfName.setText(name);
        tfURL.setText(url);
        if(out == 1)
            chbOutput.setSelected(true);
        buttCreate.setText("Reboot");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Properties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Properties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCreate;
    private javax.swing.JCheckBox chbGIT;
    private javax.swing.JCheckBox chbOutput;
    private javax.swing.JCheckBox chbSVN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labServerType;
    private javax.swing.JLabel labURL;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfURL;
    // End of variables declaration//GEN-END:variables
}
