/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package latexGraphicsForSVN;

import java.awt.Cursor;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeCellEditor;
import javax.swing.tree.TreeModel;
import latex.FileSystemModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import latex.Latex;
import latex.Svn;
import latexGlobalGraphics.loading;

/**
 *
 * @author Dwight
 */
public class SVNMenu extends javax.swing.JFrame {

    /**
     * Creates new form testGraph
     */
    private boolean _flagCTRL = false;
    private boolean _flagSync = false;
    private boolean _flagDelete = false;
    private Svn _svnCode;
    private Latex _latex;
    
    private loading _loadBar;
    
    //--------- internal variables ---------
    private String _paperName;
    private String _bibName;
    
    public SVNMenu() {
        initComponents();
        _paperName = "None";
        _bibName = "None";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        buttAddPaper = new javax.swing.JButton();
        buttAddBib = new javax.swing.JButton();
        buttEditSVN = new javax.swing.JButton();
        buttRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree.setModel(new FileSystemModel(new File("./Papers")));
        jTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMouseClicked(evt);
            }
        });
        jTree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTreeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTreeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        buttAddPaper.setText("New Paper");
        buttAddPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAddPaperActionPerformed(evt);
            }
        });

        buttAddBib.setText("New Bib");
        buttAddBib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttAddBibActionPerformed(evt);
            }
        });

        buttEditSVN.setText("Edit Svn");
        buttEditSVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEditSVNActionPerformed(evt);
            }
        });

        buttRefresh.setText("Refresh");
        buttRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttAddPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttAddBib, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttEditSVN)
                        .addGap(2, 2, 2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttAddPaper)
                    .addComponent(buttAddBib)
                    .addComponent(buttEditSVN)
                    .addComponent(buttRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTreeKeyPressed
       
        if(evt.getKeyCode() == 17){
            _flagCTRL = true;
        }
        if(_flagCTRL && !_flagDelete && evt.getKeyCode() == 83){
            _flagSync = true;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
        if(_flagCTRL && !_flagSync   && evt.getKeyCode() == 68){
            _flagDelete = true;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
        }
    }//GEN-LAST:event_jTreeKeyPressed

    private void jTreeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTreeKeyReleased
        // CTRL is 17, "s" is 83, "d" is 68
        if(evt.getKeyCode() == 116)
            refreshGraphics();
        
        if(evt.getKeyCode() == 17){
            _flagCTRL = false;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        if(evt.getKeyCode() == 83){
            _flagSync = false;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
        if(evt.getKeyCode() == 68){
            _flagDelete = false;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
           
    }//GEN-LAST:event_jTreeKeyReleased

    private void jTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMouseClicked
       //refreshGraphics();
       TreeSelectionModel a = jTree.getSelectionModel();
       TreePath[] sp = a.getSelectionPaths();
       if(sp!=null && sp.length!=0){
       int len = sp[0].toString().length();
       String paperwork="ALL",bibFile="ALL";
       String temp = sp[0].toString().substring(1,len-1);
       String[] path = temp.split(",");
       len = path.length;
       if(len > 2)
           bibFile = path[2].substring(1);
       if(len > 1)
           paperwork = path[1].substring(1);
       
      //call the sync function
       if(bibFile.contains(".bib"))
           bibFile=bibFile.substring(0,bibFile.length()-4);
       
       _paperName = paperwork;
       _bibName = bibFile;
       
       
      if(_flagSync && !jTree.isSelectionEmpty()){
          createLoadingBar("Synchronize");
          _svnCode.setContFlag(true);
          _svnCode.Synchronize(true);
          _svnCode.Synchronize(false);
          _flagSync = false;
          _flagCTRL = false;
         closeLoadingBar();
      }
      if(_flagDelete && !jTree.isSelectionEmpty()){
         
         if(_bibName.equals("ALL"))
             _svnCode.DeletePaperwork();
         else
             _svnCode.DeleteBibFile();
         refreshGraphics();
         if(_paperName.equals("ALL")){
             _svnCode.resetPapers();
         
         }
              System.out.println("delete");
         _paperName = "";
         _bibName = "";
         _flagDelete=false;
         _flagCTRL = false;
         
     }
       }
    }//GEN-LAST:event_jTreeMouseClicked

    
    public void createLoadingBar(String title){
          _loadBar = new loading();
          _loadBar.setLocation(this.getLocation());
          _loadBar.setLocation(this.getX()+10,this.getY()+100);
          _loadBar.setVisible(true);
          _loadBar.setAlwaysOnTop(true);
          _loadBar.setTitle(title);
          _loadBar.startGraphicLoading();
    }
    
    public void closeLoadingBar(){
        if(_loadBar!=null){
            _loadBar.terminateThread();
            _loadBar.dispose();
            _loadBar=null;
        }
    }
    private void changeColorBasedOnSelection(){
        String defDIR = _svnCode.GetPathForBibsInMasterDir();
        File fRoot = new File(defDIR);
        File fPaper;
        File fBib;
        TreeModel tm = jTree.getModel();
          Object fsmRoot = tm.getRoot();
          Object fsmChild;
          int indexOfChild;
          if((_paperName !=null && _paperName.equals(""))){
              
              if((_bibName !=null && _bibName.equals(""))){
                  
              }
              else{
                 
                TreeCellEditor edtr = jTree.getCellEditor();
                DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
                DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
                root.setUserObject("My label");
                model.nodeChanged(root);
              }
              //fsm = tm.
          }
    
    }
    private void buttAddPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAddPaperActionPerformed
        NewPaperworkReference p = new NewPaperworkReference();
        p.setLocation(this.getLocation());
        p.setSVN(_svnCode);
        p.setResizable(false);
        p.setDefaultCloseOperation(DISPOSE_ON_CLOSE);       
        p.setVisible(true);
        
    }//GEN-LAST:event_buttAddPaperActionPerformed

    private void buttAddBibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttAddBibActionPerformed
        if(jTree.isSelectionEmpty())
                         JOptionPane.showConfirmDialog(null,"You have to choose a project for adding a new bib file","NO SELECTION",JOptionPane.PLAIN_MESSAGE);
        else{
        BibDecision b = new BibDecision();
        b.setLocation(this.getLocation());
        b.setSVN(_svnCode);
        b.setResizable(false);
        b.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        b.setVisible(true);}
    }//GEN-LAST:event_buttAddBibActionPerformed

    private void buttEditSVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEditSVNActionPerformed
     _latex.changeProperties();
     
     _svnCode.TerminateOutput();
    }//GEN-LAST:event_buttEditSVNActionPerformed

    private void buttRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttRefreshActionPerformed
      refreshGraphics();
    }//GEN-LAST:event_buttRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVNMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVNMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVNMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVNMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVNMenu().setVisible(true);
            }
        });
    }
    
    public void setPaperName(String s){
        _paperName = s;
    }
    public String getPaperName(){
        return _paperName;
    }
    
    public void setBibName(String bib){
        _bibName = bib;
    }
    public String getBibName(){
        return _bibName;
    }
 
    public void setSVNReference(Svn svnRef){
        this._svnCode = svnRef;
    }
    
    public void setLATReference(Latex lat){
        this._latex = lat;
    }

    public void refreshGraphics(){
        jTree.setModel(new FileSystemModel(new File("./Papers")));
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttAddBib;
    private javax.swing.JButton buttAddPaper;
    private javax.swing.JButton buttEditSVN;
    private javax.swing.JButton buttRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
